import { Router } from 'express';
import { requireAuth, requirePermission } from '../middlewares/auth.middleware';
import { getActiveSeason, createSeason, addLevel, addXp, getTaskProgress, updateTaskProgress } from '../controllers/modpass.controller';
const r = Router();
r.use(requireAuth);
r.get('/active',           getActiveSeason);
r.get('/tasks/progress',   getTaskProgress);
r.post('/xp/add',          addXp);
r.post('/tasks/:id/progress', updateTaskProgress);
r.post('/seasons',         requirePermission('canManageModPass'), createSeason);
r.post('/seasons/:id/levels', requirePermission('canManageModPass'), addLevel);
export default r;
